(source "gnu" "http://elpa.gnu.org/packages/")
(source "melpa" "http://melpa.milkbox.net/packages/")

(depends-on "ag")
(depends-on "auto-complete")
(depends-on "coffee-mode")
(depends-on "column-marker")
(depends-on "enh-ruby-mode")
(depends-on "fill-column-indicator")
(depends-on "git-commit-mode")
(depends-on "grizzl")
(depends-on "haml-mode")
(depends-on "less-css-mode")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "pallet")
(depends-on "projectile")
(depends-on "rainbow-mode")
(depends-on "smartparens")
(depends-on "yaml-mode")
(depends-on "yard-mode")
(depends-on "yasnippet")
(depends-on "zenburn-theme")
