(source "melpa" "http://melpa.milkbox.net/packages/")

(depends-on "ag")
(depends-on "auto-complete")
(depends-on "color-theme")
(depends-on "column-marker")
(depends-on "enh-ruby-mode")
(depends-on "git-commit-mode")
(depends-on "grizzl")
(depends-on "haml-mode")
(depends-on "markdown-mode")
(depends-on "pallet")
(depends-on "projectile")
(depends-on "yaml-mode")
(depends-on "yard-mode")
(depends-on "yasnippet")